[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
newkycproject = "EFCNdFXKnbcoHZJEQpmKrePsCYYPeMhPoAuAtaoPNy92"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/nolanjacobson/.config/solana/privatekey.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
